#!/bin/bash

###############################################################################
#    (C) 2012 hyperclock (aka Jimmy M. Coleman)
#	 website:  www.shark-os.tk
#	 email:    hyperclock(at)sharkos-os(dot)tk
#	 git:	   https://github.com/hyperclock/sharkos-build-tool
# 
###############################################################################
###############################################################################
#    sharkos-build-tool - Scripts designed to build SharkOS based on Debian.
#
#    sharkos-build-tool is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    sharkos-build-tool is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy (see docs/gpl-3.0.txt) of the GNU General 
#    Public License along with sharkos-build-tool.  If not, see 
#    <http://www.gnu.org/licenses/>.
#
################################################################################
########################### Original Info ###################################### 
#
#    Copyright (C) 2006 - 2009  Brian Brazil
#
#    Original License: GPLv2
#
################################################################################




# This is the config for gNewSense, alter as appropriate for your own distro
# NOTE: The suggested way of changing this file is copy it to config.local and
# edit that instead.

if [ $UID != 0 ]; then
	echo 'This script must be run as root'
	exit 1
fi

# If you want less debugging information to be printed out while doing a
# Builder run, change this line to 'set +ex'
set -ex

# For kde download before anything libbogl-dev # Chris Fernandez

## UPSTREAM
# --------------------
# Debian Upstream
# -------------------
MIRROR=http://ftp.de.debian.org/debian
MIRRORDIST=wheezy

# --------------------
# Debian Security
# -------------------
MIRROR=http://security.debian.org
MIRRORDIST=wheezy/updates

# --------------------
# Debian Updates
# -------------------
MIRROR=http://ftp.de.debian.org/debian
MIRRORDIST=wheezy-updates

# --------------------
# Debian Backports
# -------------------
MIRROR=http://ftp.de.debian.org/debian
MIRRORDIST=wheezy-backports

# ------------------------
# Debian Multimedia 
# ------------------------
MEDIA_MIRROR=http://www.deb-multimedia.org
MEDIA_MIRRORDIST=wheezy

# ---------------------
#   MATE Upstream
# ----------------------
MATE_MIRROR=http://repo.mate-desktop.org/debian
MATE_MIRRORDIST=wheezy

# ---------------------
# TRINITY Uptream
# --------------------
TRINITY_MIRROR=http://ppa.quickbuild.pearsoncomputing.net/trinity/trinity-v3.5.13/debian
TRINITY_MIRRORDIST=wheezy

# -------------------------------
# TRINITY_BUILDDEPS Uptream
# -------------------------------
TRINITYBD_MIRROR=http://ppa.quickbuild.pearsoncomputing.net/trinity/trinity-builddeps-v3.5.13/debian
TRINITYBD_MIRRORDIST=wheezy



## DISTRO SPECIFIC CONFIGURATION
# May break if you use anything other than letters and numbers
# If you change $DISTRONAME you may need to modify META_desktop_ADD or create
# your own artwork packages.
DISTRONAME=SharkOS
DISTRONAME_L=`echo $DISTRONAME | tr 'A-Z' 'a-z'`
DISTNAME_FULL="SharkOS"

# What is the codename for our release?
BASE_RELEASE=megalodon
[ -z $RELEASE ] && RELEASE=$BASE_RELEASE

TAGLINE=""

# This is the 8 character key ID, not the full fingerprint
SIGNINGKEY=51FA5577

# Name and email address for changes. Syntax is important.
export MAINTINFO='SharkOS Dev Key (SharkOS Automated Development Key) <keyadmin@shark-os.tk>'

# Do you want to enable backports and updates?
UPDATES=0
BACKPORTS=0

# Which architectures will we have in our repository (list all of them)
ALL_REPO_ARCHES="i386 amd64"

## MID STREAM
# Where things go on the filesystem
BASEDIR=/srv/$DISTRONAME_L

# Where the buildscripts and livecd pull sources from
REPOAPT=http://192.168.2.5/$DISTRONAME_L

## LIVE CD
LIVECD_VERSION=7.0

## ARCHIVE AND MEDIA
# Primary mirror should be archive.$DOMAIN, secondaries are CC.archive.$DOMAIN
# Security host will be security.$DOMAIN and CC.security.$DOMAIN
# Launchpad queries are redirected to lp.$DOMAIN
# Bittorrent will use http://torrent.$DOMAIN:6969/announce
DOMAIN=shark-os.tk

# Optional bittorrent announce list (btmakemetafile.bittornado --help)
BITTORRENT_ANNOUNCE_LIST=''

# Where to push the repo and livecds
RSYNC_DEST=web3_1@repo.$DOMAIN:web/$DISTRONAME_L
RSYNC_DEST_CD=web6_1@cdimage.$DOMAIN:web/$RELEASE
# Extra options for rsyncing up cds, -va is assumed
RSYNC_OPTIONS="--partial"

## ARTWORK
LOGO_LETTER=S
LOGO_COLOUR=blue	# Don't choose black or yellow

# Changes to be made to the ubuntu-minimal etc. and packages
META_minimal_ADD=""
META_standard_ADD="emacs nethack bsdgames build-essential"
META_desktop_ADD="sharkos-artwork sharkos-gdm-themes discover read-edid"
META_desktop_ADD="${META_desktop_ADD} gthumb gnote aspell-en"
META_minimal_REMOVE=""
META_standard_REMOVE="popularity-contest friendly-recovery"
META_desktop_REMOVE="ubuntu-docs ubuntu-artwork apport-gtk hwtest-gtk usplash-theme-ubuntu ubuntu-gdm-themes"
META_desktop_REMOVE="${META_desktop_REMOVE} ubufox app-install-data-commercial"
META_desktop_REMOVE="${META_desktop_REMOVE} ubuntu-sounds"

# Packages to install on the live cd not pulled in by META_* changes
LIVECD_EXTRAS="ubiquity xresprobe binutils-static gvfs-fuse gparted jfsutils ntfsprogs xfsprogs vim"

FIREFOX_NAME=HammerHead

# Extra packages to add to the source cd
CDSOURCE_ADD="forkforge"

# Extra packages to install in the chroot
CHROOT_EXTRA_PACKAGES="aptitude cdbs python-dev python-distutils-extra python-central ccache"

# Set it to 1 if you want to use ccache in the chrooted environment.
# ccache is turned off by default because it is useful only for development
# and may increase first compilation time.
USECCACHE=1

# Version numbers to be appended to generated .debs 
# Mostly used during development (Increment these versions when making a change to the package)
DOLPHIN_KEYRING_VERSION=2
APT_VERSION=4
UBIQUITY_VERSION=5
BASE_FILES_VERSION=3
UPDATE_MANAGER_VERSION=2
ARTWORK_VERSION=2
META_VERSION=2
KERNEL_VERSION=1
LAUNCHPAD_INTEGRATION_VERSION=1
BUILDER_VERSION=1
EXAMPLE_CONTENT_VERSION=1
KDEFAULT_SETTINGS_VERSION=1
KMETA_VERSION=1
FIREFOX_VERSION=1
GNOME_DESKTOP_VERSION=2
YELP_VERSION=1
HUMAN_ICON_THEME_VERSION=1
GNOME_PANEL_VERSION=1
EPIPHANY_BROWSER_VERSION=1
PYTHON_APT_VERSION=1
LINUX_UBUNTU_MODULES_VERSION=1
APP_INSTALL_DATA_UBUNTU_VERSION=1
MODULE_INIT_TOOLS_VERSION=1
THUNDERBIRD_VERSION=1
TEXLIVE_EXTRA_VERSION=1
TEXLIVE_BIN_VERSION=1
TEXLIVE_BASE_VERSION=1
VLC_VERSION=1
CIA_SCRIPTS_VERSION=1
LIBGSM_VERSION=1

# PATHS
WORKINGDIR=$BASEDIR/tmp
# Where to put stuff for creating the livecd, and creating packages
LIVECDDIR=$BASEDIR/livecd
REPODST=$BASEDIR/$DISTRONAME_L

# Space separated list of repo components. Put the default first.
COMPONENTS="main contrib non-free"

# Allow for local customisations
if [ -r config.local ]; then . config.local; fi

if [ -r config.auto ]; then . config.auto; else exit 1; fi

# Without this, the diff cleaning for gen-linux will break. Probably affects other stuff too.
LANG=C

