#!/bin/sh -ex
# -----------------------------------------------------------------------------
#    Part of the ReForger scripts - Fork a Debian
#    Copyright (C) 2012-2013  hyperclock (aka JMColeman & the SharkOS project.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------
#
# ------------------------------- Attribution ---------------------------------
# -----------------------------------------------------------------------------
#
#    Copyright (C) 2006  Brian Brazil
#    Copyright (C) 2012  Karl Goetz
#
# -----------------------------------------------------------------------------


# Update our bzr checkout
/srv/builder/tools/update_builder.sh

# Update package lists accessed by builder
/srv/builder/tools/get-upstream-dists

# Run cronwrapper to update builder
/srv/builder/tools/cronwrapper /srv/logs/update_gnewsense \
	'cd /srv/builder/ && linux32 ./do-update && ./push-repo'

