#!/bin/bash
# -----------------------------------------------------------------------------
#    Part of the ReForger scripts - Fork a Debian
#    Copyright (C) 2012-2013  hyperclock (aka JMColeman & the SharkOS project.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------
#
# ------------------------------- Attribution ---------------------------------
# -----------------------------------------------------------------------------
#
#    Copyright (C) 2009  Karl Goetz
#
# -----------------------------------------------------------------------------

cd `dirname $0`/..
. config

# Loop through all arches in use
for GENARCH in $ALL_REPO_ARCHES; do
		# Generate contents files for each section (experimental)
		for SECTION in '' -security $EXTRAS; do
			apt-ftparchive contents $REPODST/pool |gzip > $REPODST/dists/$BASE_RELEASE$SECTION/Contents-$GENARCH.gz
		done
done
