#!/bin/bash
# -----------------------------------------------------------------------------
#    Part of the ReForger scripts - Fork a Debian
#    Copyright (C) 2012-2013  hyperclock (aka JMColeman & the SharkOS project.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------
#
# ------------------------------- Attribution ---------------------------------
# -----------------------------------------------------------------------------
#
#    Copyright (C) 2010  Sam Geeraerts
#
# -----------------------------------------------------------------------------


# This script removes everything (source, dsc, binaries) of a source package
# from the package pool.

if [ $# -ne 1 ] ; then
  echo "Usage: $(basename $0) <source package name>"
  exit 1
fi

pkg=$1

cd `dirname $0`/..
. config

for postfix in '' -security $EXTRAS ; do
  reprepro -Vb $REPODST removesrc $RELEASE$postfix $pkg
done

