#!/bin/bash
# -----------------------------------------------------------------------------
#    Part of the ReForger scripts - Fork a Debian
#    Copyright (C) 2012-2013  hyperclock (aka JMColeman & the SharkOS project.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------
#
# ------------------------------- Attribution ---------------------------------
# -----------------------------------------------------------------------------
#
#    Copyright (C) 2006  Brian Brazil
#    Copyright (C) 2013  Sam Geeraerts
#
# -----------------------------------------------------------------------------


. config
IMGDIR=$PWD/images

rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source kde4libs$VERSION
apt-get --yes build-dep kde4libs$VERSION
cd kde4libs-*

cp "$IMGDIR"/kde4libs_disable_missing_plugins.diff debian/patches/gns_disable_missing_plugins.diff
echo gns_disable_missing_plugins.diff >> debian/patches/series

echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${KDE4LIBS_VERSION}'#p' debian/changelog)  "Don't suggest downloading non-free plugins."

dpkg-buildpackage $DPKGOPTS
