#!/bin/bash
# -----------------------------------------------------------------------------
#    Part of the ReForger scripts - Fork a Debian
#    Copyright (C) 2012-2013  hyperclock (aka JMColeman & the SharkOS project.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------
#
# ------------------------------- Attribution ---------------------------------
# -----------------------------------------------------------------------------



# Get distro information
. config

mkdir -p $REPODST/conf

cd $REPODST

cat >  conf/distributions <<EOF
Origin: $DISTRONAME
Label: $DISTRONAME
Codename: ${RELEASE}-security
Update: Upstream-security
Architectures: $ALL_REPO_ARCHES source
Components: $COMP1 $COMP2 $COMP3
UDebComponents: main>$COMP1
SignWith: $SIGNINGKEY
DscIndices: Sources Release . .gz
#DebOverride: override.$RELEASE-security.bin
#UDebOverride: override.$RELEASE-security.bin
#DscOverride: override.$RELEASE-security.src

Origin: $DISTRONAME
Label: $DISTRONAME
Codename: $RELEASE
Update: Upstream Upstream-mate
Architectures: $ALL_REPO_ARCHES source
Components: $COMP1 $COMP2 $COMP3
UDebComponents: main>$COMP1
SignWith: $SIGNINGKEY
DscIndices: Sources Release . .gz
#DebOverride: override.$RELEASE.bin
#UDebOverride: override.$RELEASE.bin
#DscOverride: override.$RELEASE.src
EOF

cat >  conf/updates <<EOF
Name: Upstream-security
Method: $SEC_MIRROR
Suite: ${SEC_MIRRORDIST}-security
Components: main>$COMP1 contrib>$COMP2 non-free>$COMP2
#FilterList: install purge-hardy

Name: Upstream
Method: $MIRROR
Suite: $MIRRORDIST
Components: main>$COMP1 contrib>$COMP2 non-free>$COMP2
#FilterList: install purge-hardy

Name: Upstream-mate
Method: $MATE_MIRROR
Suite: $MATE_MIRRORDIST
Components: main>$COMP1 contrib>$COMP2 non-free>$COMP2
#FilterList: install purge-hardy
EOF

if [ 1 == $UPDATES ]; then
cat >> conf/updates <<EOF

Name: Upstream-updates
Method: $UPD_MIRROR
Suite: ${UPD_MIRRORDIST}-updates
Components: main>$COMP1 contrib>$COMP2 non-free>$COMP2
#FilterList: install purge-hardy
EOF

cat >>  conf/distributions <<EOF

Origin: $DISTRONAME
Label: $DISTRONAME
Codename: $RELEASE-updates
Update: Upstream-updates
Architectures: $ALL_REPO_ARCHES source
Components: $COMP1 $COMP2 $COMP2
UDebComponents: main
SignWith: $SIGNINGKEY
DscIndices: Sources Release . .gz
#DebOverride: override.$RELEASE-updates.bin
#UDebOverride: override.$RELEASE-updates.bin
#DscOverride: override.$RELEASE-updates.src
EOF
fi

if [ 1 == $BACKPORTS ]; then
cat >> conf/updates <<EOF

Name: Upstream-backports
Method: $BP_MIRROR
Suite: ${BP_MIRRORDIST}-backports
Components: main>$COMP1 contrib>$COMP2 non-free>$COMP2
#FilterList: install purge-hardy
EOF

cat >>  conf/distributions <<EOF

Origin: $DISTRONAME
Label: $DISTRONAME
Codename: $RELEASE-backports
Update: Upstream-backports
Architectures: $ALL_REPO_ARCHES source
Components: coast ocean deepsea
UDebComponents: main>$COMP1
SignWith: $SIGNINGKEY
DscIndices: Sources Release . .gz
#DebOverride: override.$RELEASE-backports.bin
#UDebOverride: override.$RELEASE-backports.bin
#DscOverride: override.$RELEASE-backports.src
EOF
fi;


mkdir -p $REPODST/cdimage
mkdir -p $REPODST/apt/{var,lists/partial,cache/archives/partial}
touch $REPODST/apt/status
touch conf/purge-$MIRRORDIST
