#!/bin/bash
# -----------------------------------------------------------------------------
#    Part of the ReForger scripts - Fork a Debian
#    Copyright (C) 2012-2013  hyperclock (aka JMColeman & the SharkOS project.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------
#
# ------------------------------- Attribution ---------------------------------
# -----------------------------------------------------------------------------
#
#    Copyright (C) 2008 Brian Brazil
#
# -----------------------------------------------------------------------------

. config

rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source epiphany-browser$VERSION
apt-get --yes build-dep epiphany-browser$VERSION
cd epiphany-browser-*

sed -i "s#homepage .*#homepage http://www.$DOMAIN#" debian/epiphany-browser-data.gconf-defaults

sed -i '/^07_bookmarks/d' debian/patches/series
rm debian/patches/07_bookmarks.patch

echo | dch -D $RELEASE -v $(sed -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${EPIPHANY_BROWSER_VERSION}'#p' debian/changelog)  "Changed homepage"

dpkg-buildpackage $DPKGOPTS
