#!/bin/bash
# -----------------------------------------------------------------------------
#    Part of the ReForger scripts - Fork a Debian
#    Copyright (C) 2012-2013  hyperclock (aka JMColeman & the SharkOS project.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------
#
# ------------------------------- Attribution ---------------------------------
# -----------------------------------------------------------------------------
#
#    Copyright (C) 2010 Karl Goetz
#
# -----------------------------------------------------------------------------


. config

rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source apt
apt-get --yes build-dep apt
cd apt-*

rm doc/examples/sources.list
cat << EOF >> doc/examples/sources.list
# See sources.list(5) for more information, especialy
# Remember that you can only use http, ftp or file URIs
# CDROMs are managed through the apt-cdrom tool.
deb http://repo.$DOMAIN/$DISTRONAME_L $BASE_RELEASE $COMP1 $COMP2 $COMP3
deb-src http://repo.$DOMAIN/$DISTRONAME_L $BASE_RELEASE $COMP1 $COMP2 $COMP3

deb http://security.$DOMAIN/$DISTRONAME_L $BASE_RELEASE-security $COMP1 $COMP2 $COMP3
deb-src http://security.$DOMAIN/$DISTRONAME_L $BASE_RELEASE-security $COMP1 $COMP2 $COMP3

deb http://repo.$DOMAIN/$DISTRONAME_L $BASE_RELEASE-updates $COMP1 $COMP2 $COMP3
deb-src http://repo.$DOMAIN/$DISTRONAME_L $BASE_RELEASE-updates $COMP1 $COMP2 $COMP3
EOF

echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${APT_VERSION}'#p' debian/changelog) "Changed for $DISTRONAME"

dpkg-buildpackage $DPKGOPTS
