#!/bin/bash
# -----------------------------------------------------------------------------
#    Part of the ReForger scripts - Fork a Debian
#    Copyright (C) 2012-2013  hyperclock (aka JMColeman & the SharkOS project.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------
#
# ------------------------------- Attribution ---------------------------------
# -----------------------------------------------------------------------------
#
#    Copyright (C) 2009  Karl Goetz
#
# -----------------------------------------------------------------------------


. config

IMGDIR=$PWD/images
rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source texlive-bin
rm *.orig.*
apt-get --yes build-dep texlive-bin
cd texlive-bin-*

# Find nonfree font downloader and remove it.
find ./ -name *nonfree* -exec rm -v {} +

# Remove references (as needed) in files
sed -i -e '/#60_getnonfreefonts_bash/d' debian/patches/series
sed -i -e '/getnonfreefonts/d' debian/control
sed -i -e '/getnonfreefonts-sys/d' build/source/texk/texlive/Makefile.in
sed -i -e 's/getnonfreefonts//g' build/source/texk/texlive/Makefile.in

echo | dch -D $RELEASE -v $(sed -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${TEXLIVE_BASE_VERSION}'#p' debian/changelog)  'Inserted new licence file'

dpkg-buildpackage $DPKGOPTS

